import { createContext, useContext, useMemo, useState } from 'react';

const translations = {
  en: {
    langLabel: 'Language',
    navUpload: 'Upload',
    navChat: 'Chat',
    navSummary: 'Summary',
    navDocuments: 'Documents',
    navAnalytics: 'Analytics',
    serverOnline: 'Server online',
    sampleQ1: 'What are the key obligations in this policy?',
    sampleQ2: 'Summarize the main risks and exceptions.',
    sampleQ3: 'Show me the clauses related to compliance.',
    clearChat: 'Clear',
    chatTitle: 'Ask about your policy documents',
    chatSubtitle: 'Upload a policy and ask questions in natural language.',
    suggestedQuestions: 'Suggested questions',
    inputPlaceholder: 'Ask a question about the policy...',
    docsTitle: 'Documents',
    docsSubtitle: 'Manage uploaded policy PDFs and review their content.',
    uploadTitle: 'Upload a policy',
    uploadSubtitle: 'Drop a PDF to index it for search and summarization.',
    searchPlaceholder: 'Search documents...',
    filterAll: 'All',
    noDocs: 'No documents yet',
    deleteDoc: 'Delete',
    selectDoc: 'Select a document',
    generateSummary: 'Generate summary',
    summaryTitle: 'Policy summary',
    summarySubtitle: 'Generate structured summaries for your policies.',
    exportJson: 'Export JSON',
    copyAnswer: 'Copy answer',
    stopSpeech: 'Stop speech',
    readAloud: 'Read aloud',
    sourcesHeading: 'Sources',
    analyticsTitle: 'Analytics Dashboard',
    analyticsSubtitle: 'Real-time usage statistics, document insights, and system health.',
    totalDocs: 'Total Documents',
    totalPages: 'Total Pages',
    totalSize: 'Storage Used',
    queryCount: 'Queries Processed',
    langBreakdown: 'Language Breakdown',
    systemStatus: 'System Status',
    recentActivity: 'Recent Activity',
    noActivity: 'No queries yet',
    vectorStore: 'Vector Store',
    faissIndex: 'FAISS Index',
    chunkCount: 'Indexed Chunks',
    keyPoints: 'Key points',
    sections: 'Sections',
    importantDates: 'Important dates',
    actionItems: 'Action items',
    executiveSummary: 'Executive summary',
    uploadDropzoneTitle: 'Upload Policy Document',
    uploadDropzoneDropHere: 'Drop Policy PDF Here',
    uploadDropzoneInstructions: 'Drag & drop your PDF file or click to browse. Max size 25MB.',
    uploadDropzonePdfSupported: 'PDF Documents Supported',
    uploadAnalyzing: 'Analyzing Policy Document... {progress}%',
    uploadSuccess: 'Successfully processed {file}! Ready for Q&A and summary.',
    heroBadge: 'Smart Multi-Language Policy Intelligence (EN / HI / MR)',
    docsReadySingle: '{count} Policy Document Ready',
    docsReadyPlural: '{count} Policy Documents Ready',
    docsReadySubtitle: 'Policy documents processed — ready for multi-language Q&A and AI summaries.',
    howItWorks: 'How PolicyPilot Works',
    step1Title: 'Upload & Read',
    step1Desc: 'Document text is analyzed and language is auto-detected (EN/HI/MR).',
    step2Title: 'Smart Indexing',
    step2Desc: 'Text content is structured into search segments for instant retrieval.',
    step3Title: 'Instant Q&A',
    step3Desc: 'Ask questions and receive precise answers with verified document citations.',
    feature1Title: 'Tri-Lingual Support',
    feature1Desc: 'Full support for English, Hindi (हिन्दी), and Marathi (मराठी) for document ingestion, Q&A, and structured summaries.',
    feature2Title: 'Verifiable Citations',
    feature2Desc: 'Every answer includes exact page-level citations, similarity scores, and verifiable confidence ratings.',
    feature3Title: 'Instant Search Engine',
    feature3Desc: 'High-speed semantic search for instant answers across long policy documents.',
    uploadToastSuccess: '"{file}" processed successfully! {pages}',
    
    // Page specific translations
    analyticsInsights: 'Real-Time Platform Insights',
    refreshBtn: 'Refresh',
    analyticsLoadError: 'Could not load analytics. Make sure the backend is running.',
    docsInSystem: 'Policy documents in system',
    pagesProcessed: 'Document pages processed',
    queriesAnswered: 'Q&A queries answered',
    storageConsumed: 'Total storage consumed',
    noDocsUploaded: 'No documents uploaded yet. Upload PDFs to see language distribution.',
    apiServer: 'API Server',
    dbStorage: 'Database Storage',
    searchIndexTitle: 'Search Index',
    multiLangEngineStatus: 'Multi-Language Engine',
    docParser: 'Document Parser',
    lastUpdated: 'Last updated',
    operational: 'Operational',
    degraded: 'Degraded',
    smartSearchIdx: 'Smart Search Index',
    smartSearchDesc: 'High-speed similarity search for retrieving relevant policy clauses instantly across thousands of pages.',
    multiLangEngine: 'Multi-Language Engine',
    multiLangDesc: 'Multilingual semantic processing supporting English, Hindi (हिन्दी), and Marathi (मराठी).',
    aiAnalysis: 'AI Analysis Engine',
    aiAnalysisDesc: 'Delivers rapid Q&A responses and structured executive summaries with verifiable document citations.',
    askViaChat: 'Ask questions via the Chat interface and they will appear here.',
    policyScope: 'Policy Scope',
    policySelection: 'Policy Selection',
    allPolicyDocs: 'All Policy Documents',
    analyzingDocs: 'Analyzing policy documents & preparing response...',
    deleteConfirm: 'Delete "{name}"? This will remove it from FAISS.',
    deleteSuccessText: '"{name}" deleted successfully.',
    deleteFailed: 'Failed to delete document. Please try again.',
    uploadPdfPrompt: 'Upload your policy PDFs to extract chunks, generate vector embeddings, and enable tri-lingual search.',
    viewDetailsBtn: 'View Details',
    docNotFoundLoad: 'Document not found or failed to load.',
    backToDocs: 'Back to Documents',
    backToDocsList: 'Back to Documents List',
    docNotFound: 'Document not found',
    policyDocId: 'Policy Document ID #',
    chunks: 'Chunks',
    languagePrefix: 'Language',
    uploadedPrefix: 'Uploaded',
    askQuestionsChat: 'Ask Questions in Chat',
    refreshSummaryBtn: 'Refresh Summary',
    generateSummaryBtnLabel: 'Generate Summary',
    multiLangSummarizer: 'Multi-Language Policy Summarizer',
    selectDocPlaceholder: '-- Select a document',
    available: 'available',
    pagesLabel: 'pages',
    genSummaryFailed: 'Failed to generate summary.',
    generatingSummary: 'Generating Tri-Lingual Summary...',
    extractingPoints: 'Extracting key policy points, section briefs, dates, and compliance steps...',

    // Component specific translations
    policyAssistant: 'Policy Assistant',
    helpfulResponse: 'Helpful response',
    needsImprovement: 'Needs improvement',
    highConfidence: 'High Confidence',
    mediumConfidence: 'Medium Confidence',
    lowConfidence: 'Low Confidence',
    confidenceScoreTooltip: 'Confidence Score: {percent}% based on semantic context match',
    multiLanguage: 'Multi-Language',
    relatedPolicyDocs: 'Related Policy Documents',
    pageLabel: 'Page',
    scoreLabel: 'Score:',
    viewFullDoc: 'View Full Document',
    policyExecBrief: 'Policy Executive Brief',
    copied: 'Copied',
    uploadProcessError: 'Failed to process document. Please check PDF validity.',
    speechNotSupported: 'Speech recognition is not supported in this browser. Please use Chrome or Edge.',
    listeningStop: 'Listening... Click to stop',
    clickToSpeak: 'Click to speak question aloud'
  },
  hi: {
    langLabel: 'भाषा',
    navUpload: 'अपलोड',
    navChat: 'चैट',
    navSummary: 'सारांश',
    navDocuments: 'दस्तावेज़',
    navAnalytics: 'विश्लेषण',
    serverOnline: 'सर्वर ऑनलाइन',
    sampleQ1: 'इस नीति में मुख्य दायित्व क्या हैं?',
    sampleQ2: 'मुख्य जोखिम और अपवादों का सारांश बताइए।',
    sampleQ3: 'Compliance से संबंधित धाराओं को दिखाइए।',
    clearChat: 'साफ करें',
    chatTitle: 'अपने नीति दस्तावेजों के बारे में पूछें',
    chatSubtitle: 'एक नीति अपलोड करें और प्राकृतिक भाषा में प्रश्न पूछें।',
    suggestedQuestions: 'सुझाए गए प्रश्न',
    inputPlaceholder: 'नीति के बारे में कोई प्रश्न पूछें...',
    docsTitle: 'दस्तावेज़',
    docsSubtitle: 'अपलोड किए गए PDF प्रबंधित करें और उनकी सामग्री देखें।',
    uploadTitle: 'नीति अपलोड करें',
    uploadSubtitle: 'खोज और सारांश के लिए PDF डालें।',
    searchPlaceholder: 'दस्तावेज़ खोजें...',
    filterAll: 'सभी',
    noDocs: 'अभी कोई दस्तावेज़ नहीं',
    deleteDoc: 'हटाएं',
    selectDoc: 'एक दस्तावेज़ चुनें',
    generateSummary: 'सारांश बनाएं',
    summaryTitle: 'नीति सारांश',
    summarySubtitle: 'अपनी नीतियों के लिए संरचित सारांश बनाएँ।',
    exportJson: 'JSON निर्यात करें',
    copyAnswer: 'उत्तर कॉपी करें',
    stopSpeech: 'भाषण रोकें',
    readAloud: 'जोर से पढ़ें',
    sourcesHeading: 'स्रोत',
    analyticsTitle: 'विश्लेषण डैशबोर्ड',
    analyticsSubtitle: 'वास्तविक समय उपयोग आँकड़े, दस्तावेज़ जानकारी, और सिस्टम स्थिति।',
    totalDocs: 'कुल दस्तावेज़',
    totalPages: 'कुल पृष्ठ',
    totalSize: 'संग्रहण उपयोग',
    queryCount: 'प्रश्न संसाधित',
    langBreakdown: 'भाषा विभाजन',
    systemStatus: 'सिस्टम स्थिति',
    recentActivity: 'हालिया गतिविधि',
    noActivity: 'अभी तक कोई प्रश्न नहीं',
    vectorStore: 'वेक्टर स्टोर',
    faissIndex: 'FAISS इंडेक्स',
    chunkCount: 'अनुक्रमित खंड',
    keyPoints: 'मुख्य बिंदु',
    sections: 'अनुभाग',
    importantDates: 'महत्वपूर्ण तिथियाँ',
    actionItems: 'कार्रवाई की वस्तुएँ',
    executiveSummary: 'कार्यकारी सारांश',
    uploadDropzoneTitle: 'नीति दस्तावेज़ अपलोड करें',
    uploadDropzoneDropHere: 'यहां नीति PDF ड्रॉप करें',
    uploadDropzoneInstructions: 'अपना PDF फ़ाइल ड्रैग और ड्रॉप करें या ब्राउज़ करने के लिए क्लिक करें। अधिकतम आकार 25MB।',
    uploadDropzonePdfSupported: 'PDF दस्तावेज़ समर्थित',
    uploadAnalyzing: 'नीति दस्तावेज़ विश्लेषित कर रहा है... {progress}%',
    uploadSuccess: 'सफलतापूर्वक संसाधित {file}! Q&A और सारांश के लिए तैयार।',
    heroBadge: 'स्मार्ट मल्टी-भाषा नीति इंटेलिजेंस (EN / HI / MR)',
    docsReadySingle: '{count} नीति दस्तावेज़ तैयार है',
    docsReadyPlural: '{count} नीति दस्तावेज़ तैयार हैं',
    docsReadySubtitle: 'नीति दस्तावेज़ संसाधित किए गए — मल्टी-भाषा Q&A और AI सारांश के लिए तैयार।',
    howItWorks: 'PolicyPilot कैसे काम करता है',
    step1Title: 'अपलोड और पढ़ें',
    step1Desc: 'दस्तावेज़ पाठ का विश्लेषण किया जाता है और भाषा स्वचालित रूप से पहचान ली जाती है (EN/HI/MR)।',
    step2Title: 'स्मार्ट इंडेक्सिंग',
    step2Desc: 'तत्काल पुन:प्राप्ति के लिए टेक्स्ट सामग्री को खोज खंडों में संरचित किया जाता है।',
    step3Title: 'तुरंत Q&A',
    step3Desc: 'प्रश्न पूछें और सत्यापित दस्तावेज़ उद्धरणों के साथ सटीक उत्तर प्राप्त करें।',
    feature1Title: 'त्रि-भाषीय समर्थन',
    feature1Desc: 'डॉक्युमेंट इनजेशन, Q&A और संरचित सारांश के लिए अंग्रेज़ी, हिंदी (हिन्दी) और मराठी (मराठी) का पूर्ण समर्थन।',
    feature2Title: 'सत्यापन योग्य उद्धरण',
    feature2Desc: 'हर उत्तर में सटीक पृष्ठ-स्तर उद्धरण, सादृश्य स्कोर, और सत्यापित आत्मविश्वास रेटिंग शामिल हैं।',
    feature3Title: 'तुरंत खोज इंजन',
    feature3Desc: 'लंबे नीति दस्तावेज़ों में त्वरित उत्तरों के लिए उच्च-गति सेमांटिक खोज।',
    uploadToastSuccess: '"{file}" सफलतापूर्वक संसाधित! {pages}',

    // Page specific translations
    analyticsInsights: 'रियल-टाइम प्लेटफ़ॉर्म इनसाइट्स',
    refreshBtn: 'रिफ्रेश करें',
    analyticsLoadError: 'एनालिटिक्स लोड नहीं हो सका। सुनिश्चित करें कि बैकएंड चल रहा है।',
    docsInSystem: 'सिस्टम में नीति दस्तावेज़',
    pagesProcessed: 'संसाधित दस्तावेज़ पृष्ठ',
    queriesAnswered: 'Q&A प्रश्नों के उत्तर दिए गए',
    storageConsumed: 'कुल संग्रहण का उपयोग',
    noDocsUploaded: 'अभी तक कोई दस्तावेज़ अपलोड नहीं किया गया। भाषा वितरण देखने के लिए PDF अपलोड करें।',
    apiServer: 'API सर्वर',
    dbStorage: 'डेटाबेस स्टोरेज',
    searchIndexTitle: 'खोज इंडेक्स',
    multiLangEngineStatus: 'मल्टी-लेंग्वेज इंजन',
    docParser: 'दस्तावेज़ पार्सर',
    lastUpdated: 'अंतिम अपडेट',
    operational: 'सक्रिय',
    degraded: 'खराब',
    smartSearchIdx: 'स्मार्ट सर्च इंडेक्स',
    smartSearchDesc: 'हजारों पृष्ठों में प्रासंगिक नीतिगत खंडों को तुरंत प्राप्त करने के लिए उच्च गति वाली समानता खोज।',
    multiLangEngine: 'मल्टी-लेंग्वेज इंजन',
    multiLangDesc: 'अंग्रेजी, हिंदी और मराठी का समर्थन करने वाला बहुभाषी सिमेंटिक प्रोसेसिंग।',
    aiAnalysis: 'AI विश्लेषण इंजन',
    aiAnalysisDesc: 'सत्यापन योग्य दस्तावेज़ उद्धरणों के साथ तेज़ Q&A प्रतिक्रियाएँ और संरचित सारांश प्रदान करता है।',
    askViaChat: 'चैट इंटरफ़ेस के माध्यम से प्रश्न पूछें और वे यहां दिखाई देंगे।',
    policyScope: 'नीति का दायरा',
    policySelection: 'नीति चयन',
    allPolicyDocs: 'सभी नीति दस्तावेज़',
    analyzingDocs: 'नीति दस्तावेज़ों का विश्लेषण और उत्तर तैयार किया जा रहा है...',
    deleteConfirm: 'क्या "{name}" को हटाना है? यह इसे FAISS से हटा देगा।',
    deleteSuccessText: '"{name}" सफलतापूर्वक हटा दिया गया।',
    deleteFailed: 'दस्तावेज़ हटाने में विफल। कृपया पुनः प्रयास करें।',
    uploadPdfPrompt: 'विभाजन निकालने, वेक्टर एम्बेडिंग बनाने और त्रि-भाषीय खोज को सक्षम करने के लिए अपने नीति PDF अपलोड करें।',
    viewDetailsBtn: 'विवरण देखें',
    docNotFoundLoad: 'दस्तावेज़ नहीं मिला या लोड होने में विफल रहा।',
    backToDocs: 'दस्तावेज़ों पर वापस जाएं',
    backToDocsList: 'दस्तावेज़ सूची पर वापस जाएं',
    docNotFound: 'दस्तावेज़ नहीं मिला',
    policyDocId: 'नीति दस्तावेज़ आईडी #',
    chunks: 'खंड',
    languagePrefix: 'भाषा',
    uploadedPrefix: 'अपलोड किया गया',
    askQuestionsChat: 'चैट में प्रश्न पूछें',
    refreshSummaryBtn: 'सारांश रिफ्रेश करें',
    generateSummaryBtnLabel: 'सारांश बनाएँ',
    multiLangSummarizer: 'मल्टी-लेंग्वेज नीति सारांशकर्ता',
    selectDocPlaceholder: '-- एक दस्तावेज़ चुनें',
    available: 'उपलब्ध',
    pagesLabel: 'पृष्ठ',
    genSummaryFailed: 'सारांश बनाने में विफल।',
    generatingSummary: 'त्रि-भाषीय सारांश बनाया जा रहा है...',
    extractingPoints: 'मुख्य नीति बिंदु, अनुभाग सारांश, तिथियां और अनुपालन चरण निकाले जा रहे हैं...',

    // Component specific translations
    policyAssistant: 'नीति सहायक',
    helpfulResponse: 'मददगार उत्तर',
    needsImprovement: 'सुधार की आवश्यकता है',
    highConfidence: 'उच्च आत्मविश्वास',
    mediumConfidence: 'मध्यम आत्मविश्वास',
    lowConfidence: 'कम आत्मविश्वास',
    confidenceScoreTooltip: 'आत्मविश्वास स्कोर: सिमेंटिक संदर्भ मिलान के आधार पर {percent}%',
    multiLanguage: 'मल्टी-भाषा',
    relatedPolicyDocs: 'संबंधित नीति दस्तावेज़',
    pageLabel: 'पृष्ठ',
    scoreLabel: 'स्कोर:',
    viewFullDoc: 'पूरा दस्तावेज़ देखें',
    policyExecBrief: 'नीति कार्यकारी संक्षेप',
    copied: 'कॉपी किया गया',
    uploadProcessError: 'दस्तावेज़ संसाधित करने में विफल। कृपया PDF वैधता जांचें।',
    speechNotSupported: 'इस ब्राउज़र में स्पीच रिकग्निशन समर्थित नहीं है। कृपया Chrome या Edge का उपयोग करें।',
    listeningStop: 'सुन रहा है... रोकने के लिए क्लिक करें',
    clickToSpeak: 'प्रश्न जोर से बोलने के लिए क्लिक करें'
  },
  mr: {
    langLabel: 'भाषा',
    navUpload: 'अपलोड',
    navChat: 'चॅट',
    navSummary: 'सारांश',
    navDocuments: 'दस्तऐवज',
    navAnalytics: 'विश्लेषण',
    serverOnline: 'सर्वर ऑनलाइन',
    sampleQ1: 'या धोरणात मुख्य जबाबदाऱ्या काय आहेत?',
    sampleQ2: 'मुख्य जोखीम आणि अपवादांचा सारांश सांगा.',
    sampleQ3: 'Compliance संबंधित तरतुदी दाखवा.',
    clearChat: 'स्वच्छ करा',
    chatTitle: 'तुमच्या धोरण दस्तऐवजांबद्दल विचारा',
    chatSubtitle: 'धोरण अपलोड करा आणि नैसर्गिक भाषेत प्रश्न विचारा.',
    suggestedQuestions: 'सूचित केलेले प्रश्न',
    inputPlaceholder: 'धोरणाबद्दल प्रश्न विचारा...',
    docsTitle: 'दस्तऐवज',
    docsSubtitle: 'अपलोड केलेले PDF व्यवस्थापित करा आणि त्यांची सामग्री पहा.',
    uploadTitle: 'धोरण अपलोड करा',
    uploadSubtitle: 'शोध आणि सारांशासाठी PDF टाका.',
    searchPlaceholder: 'दस्तऐवज शोधा...',
    filterAll: 'सर्व',
    noDocs: 'अद्याप कोणतेही दस्तऐवज नाहीत',
    deleteDoc: 'हटवा',
    selectDoc: 'एक दस्तऐवज निवडा',
    generateSummary: 'सारांश तयार करा',
    summaryTitle: 'धोरण सारांश',
    summarySubtitle: 'तुमच्या धोरणांसाठी संरचित सारांश तयार करा.',
    exportJson: 'JSON निर्यात करा',
    copyAnswer: 'उत्तर कॉपी करा',
    stopSpeech: 'भाषण थांबवा',
    readAloud: 'जोरात वाचा',
    sourcesHeading: 'स्रोत',
    analyticsTitle: 'विश्लेषण डॅशबोर्ड',
    analyticsSubtitle: 'रिअल-टाइम वापर आकडेवारी, दस्तऐवज माहिती, आणि सिस्टम स्थिती.',
    totalDocs: 'एकूण दस्तऐवज',
    totalPages: 'एकूण पृष्ठे',
    totalSize: 'स्टोरेज वापर',
    queryCount: 'प्रश्न प्रक्रिया केली',
    langBreakdown: 'भाषा विभाजन',
    systemStatus: 'सिस्टम स्थिती',
    recentActivity: 'अलीकडील क्रियाकलाप',
    noActivity: 'अजून कोणतेही प्रश्न नाहीत',
    vectorStore: 'व्हेक्टर स्टोर',
    faissIndex: 'FAISS इंडेक्स',
    chunkCount: 'अनुक्रमित खंड',
    keyPoints: 'मुख्य मुद्दे',
    sections: 'विभाग',
    importantDates: 'महत्वाच्या तारखा',
    actionItems: 'कृती आयटम',
    executiveSummary: 'कार्यकारी सारांश',
    uploadDropzoneTitle: 'धोरण दस्तऐवज अपलोड करा',
    uploadDropzoneDropHere: 'इथे धोरण PDF टाका',
    uploadDropzoneInstructions: 'आपले PDF फाईल ड्रॅग आणि ड्रॉप करा किंवा ब्राउझ करण्यासाठी क्लिक करा. जास्तीत जास्त आकार 25MB.',
    uploadDropzonePdfSupported: 'PDF दस्तऐवज समर्थित आहेत',
    uploadAnalyzing: 'धोरण दस्तऐवजाचे विश्लेषण करीत आहे... {progress}%',
    uploadSuccess: 'यशस्वीरित्या प्रक्रियेत आलेले {file}! Q&A आणि सारांशासाठी तयार.',
    heroBadge: 'स्मार्ट मल्टी-लॅंग्वेज धोरण इंटेलिजन्स (EN / HI / MR)',
    docsReadySingle: '{count} धोरण दस्तऐवज तयार आहे',
    docsReadyPlural: '{count} धोरण दस्तऐवज तयार आहेत',
    docsReadySubtitle: 'धोरण दस्तऐवज प्रक्रिया केले गेले — मल्टी-लॅंग्वेज Q&A आणि AI सारांशांसाठी तयार.',
    howItWorks: 'PolicyPilot कशी काम करते',
    step1Title: 'अपलोड & वाचा',
    step1Desc: 'दस्तऐवज मजकूराचे विश्लेषण केले जाते आणि भाषा आपोआप ओळखली जाते (EN/HI/MR).',
    step2Title: 'स्मार्ट इंडेक्सिंग',
    step2Desc: 'त्वरित पुनर्प्राप्तीसाठी मजकूर सामग्री शोध विभागांमध्ये संरचित केली जाते.',
    step3Title: 'तुरंत Q&A',
    step3Desc: 'प्रश्न विचारा आणि सत्यापित दस्तऐवज उद्धरणांसह अचूक उत्तरे मिळवा.',
    feature1Title: 'त्रि-भाषीय समर्थन',
    feature1Desc: 'डॉक्युमेंट इन्जेक्शन, Q&A आणि संरचित सारांशांसाठी इंग्रजी, हिंदी (हिन्दी), आणि मराठी (मराठी) यांचा पूर्ण सपोर्ट.',
    feature2Title: 'सत्यापनीय उद्धरण',
    feature2Desc: 'प्रत्येक उत्तरात अचूक पृष्ठ-स्तर उद्धरण, सादृश्यता स्कोअर्स आणि सत्यापित आत्मविश्वास रेटिंग्स असतात.',
    feature3Title: 'तुरित शोध इंजिन',
    feature3Desc: 'लांब धोरण दस्तऐवजांमध्ये त्वरित उत्तरांसाठी उच्च-गती सेमँटिक शोध.',
    uploadToastSuccess: '"{file}" यशस्वीरित्या प्रक्रिया केले! {pages}',

    // Page specific translations
    analyticsInsights: 'रिअल-टाइम प्लॅटफॉर्म इनसाइट्स',
    refreshBtn: 'रिफ्रेश करा',
    analyticsLoadError: 'अ‍ॅनालिटिक्स लोड होऊ शकले नाही. बॅकएंड चालू असल्याची खात्री करा.',
    docsInSystem: 'सिस्टममधील धोरण दस्तऐवज',
    pagesProcessed: 'प्रक्रिया केलेली दस्तऐवज पृष्ठे',
    queriesAnswered: 'Q&A प्रश्नांची उत्तरे दिली',
    storageConsumed: 'एकूण स्टोरेज वापर',
    noDocsUploaded: 'अद्याप कोणतेही दस्तऐवज अपलोड केलेले नाहीत. भाषा वितरण पाहण्यासाठी PDF अपलोड करा.',
    apiServer: 'API सर्व्हर',
    dbStorage: 'डेटाबेस स्टोरेज',
    searchIndexTitle: 'शोध इंडेक्स',
    multiLangEngineStatus: 'मल्टी-लँग्वेज इंजिन',
    docParser: 'दस्तऐवज पार्सर',
    lastUpdated: 'अंतिम अपडेट',
    operational: 'सक्रिय',
    degraded: 'खराब',
    smartSearchIdx: 'स्मार्ट सर्च इंडेक्स',
    smartSearchDesc: 'हजारो पृष्ठांवर त्वरित संबंधित धोरण कलमे मिळवण्यासाठी उच्च-गती समानता शोध.',
    multiLangEngine: 'मल्टी-लँग्वेज इंजिन',
    multiLangDesc: 'इंग्रजी, हिंदी आणि मराठीला सपोर्ट करणारे बहुभाषिक सिमेंटिक प्रोसेसिंग.',
    aiAnalysis: 'AI विश्लेषण इंजिन',
    aiAnalysisDesc: 'सत्यापनीय दस्तऐवज उद्धरणांसह जलद Q&A प्रतिसाद आणि संरचित सारांश प्रदान करते.',
    askViaChat: 'चॅट इंटरफेसद्वारे प्रश्न विचारा आणि ते येथे दिसतील.',
    policyScope: 'धोरणाची व्याप्ती',
    policySelection: 'धोरण निवड',
    allPolicyDocs: 'सर्व धोरण दस्तऐवज',
    analyzingDocs: 'धोरण दस्तऐवजांचे विश्लेषण आणि उत्तर तयार केले जात आहे...',
    deleteConfirm: '"{name}" हटवायचे? हे FAISS मधून काढून टाकेल.',
    deleteSuccessText: '"{name}" यशस्वीरित्या हटवले गेले.',
    deleteFailed: 'दस्तऐवज हटवण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
    uploadPdfPrompt: 'खंड काढण्यासाठी, वेक्टर एम्बेडिंग्ज तयार करण्यासाठी आणि त्रि-भाषिक शोध सक्षम करण्यासाठी तुमचे धोरण PDF अपलोड करा.',
    viewDetailsBtn: 'तपशील पहा',
    docNotFoundLoad: 'दस्तऐवज सापडला नाही किंवा लोड करण्यात अयशस्वी.',
    backToDocs: 'दस्तऐवजांवर परत जा',
    backToDocsList: 'दस्तऐवज सूचीवर परत जा',
    docNotFound: 'दस्तऐवज सापडला नाही',
    policyDocId: 'धोरण दस्तऐवज आयडी #',
    chunks: 'खंड',
    languagePrefix: 'भाषा',
    uploadedPrefix: 'अपलोड केले',
    askQuestionsChat: 'चॅटमध्ये प्रश्न विचारा',
    refreshSummaryBtn: 'सारांश रिफ्रेश करा',
    generateSummaryBtnLabel: 'सारांश तयार करा',
    multiLangSummarizer: 'मल्टी-लँग्वेज धोरण सारांशकर्ता',
    selectDocPlaceholder: '-- एक दस्तऐवज निवडा',
    available: 'उपलब्ध',
    pagesLabel: 'पृष्ठे',
    genSummaryFailed: 'सारांश तयार करण्यात अयशस्वी.',
    generatingSummary: 'त्रि-भाषिक सारांश तयार करत आहे...',
    extractingPoints: 'मुख्य धोरण मुद्दे, विभाग सारांश, तारखा आणि अनुपालन टप्पे काढत आहे...',

    // Component specific translations
    policyAssistant: 'धोरण सहाय्यक',
    helpfulResponse: 'मदतगार उत्तर',
    needsImprovement: 'सुधारणा आवश्यक',
    highConfidence: 'उच्च आत्मविश्वास',
    mediumConfidence: 'मध्यम आत्मविश्वास',
    lowConfidence: 'कमी आत्मविश्वास',
    confidenceScoreTooltip: 'आत्मविश्वास स्कोर: सिमेंटिक संदर्भ जुळणीवर आधारित {percent}%',
    multiLanguage: 'मल्टी-लँग्वेज',
    relatedPolicyDocs: 'संबंधित धोरण दस्तऐवज',
    pageLabel: 'पृष्ठ',
    scoreLabel: 'स्कोअर:',
    viewFullDoc: 'पूर्ण दस्तऐवज पहा',
    policyExecBrief: 'धोरण कार्यकारी संक्षिप्त',
    copied: 'कॉपी केले',
    uploadProcessError: 'दस्तऐवज प्रक्रिया करण्यात अयशस्वी. कृपया PDF वैधतेची तपासणी करा.',
    speechNotSupported: 'या ब्राउझरमध्ये स्पीच रेकग्निशन समर्थित नाही. कृपया Chrome किंवा Edge वापरा.',
    listeningStop: 'ऐकत आहे... थांबवण्यासाठी क्लिक करा',
    clickToSpeak: 'प्रश्न मोठ्याने बोलण्यासाठी क्लिक करा'
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const value = useMemo(() => {
    const dict = translations[language] || translations.en;
    return {
      language,
      setLanguage,
      t: (key) => dict[key] || translations.en[key] || key,
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return ctx;
}

export default LanguageContext;